services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "8084:80"
            - "4047:443"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        networks:
            icomplex_test:
                ipv4_address: 172.33.1.1

    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: icomplex_test
            MYSQL_ROOT_PASSWORD: root
        networks:
            icomplex_test:
                ipv4_address: 172.33.1.2

networks:
    icomplex_test:
        ipam:
            driver: default
            config:
                - subnet: 172.33.0.0/16
